@startuml ディナー
start
fork
    :カレールーとジャガイモとにんじんと玉ねぎを買う
    担当者　太郎;
    :カレーとライスを作る
    担当者　太郎;
    :盛り付ける
    担当者　太郎;
fork again
    : キャベツを買う
    担当者　花子;
    : キャベツを切る
    担当者　花子;
    : ドレッシングをかけて、盛り付ける
    担当者　花子;
fork again
    : 玉ねぎを切る
    担当者　次郎;
    : お湯にコンソメと玉ねぎを入れる
    担当者　次郎;
    : 盛り付ける
    担当者　次郎;

end fork

stop
@enduml
