
@startwbs 豪華な夕食を作る
* 豪華な夕食を作る
**[#LightBlue] カレーライスを作る
***[#Yellow] カレールーとじゃがいもとにんじんと玉ねぎを買う
***[#Yellow] カレーとライスを作る
***[#Yellow] 盛り付ける
**[#LightBlue] 和風サラダを作る
***[#Yellow] キャベツを買う
***[#Yellow] キャベツを切って
***[#Yellow] ドレッシングをかけて、盛り付ける
**[#LightBlue] コンソメスープを作る
***[#Yellow] 玉ねぎを切る
***[#Yellow] お湯にコンソメと玉ねぎを入れる
***[#Yellow] 盛り付ける
@endwbs